export const categories = [
  {
    title: "Consumer Goods",
    icon: "fa6-solid:bag-shopping",
    key: "consumer-goods",
    url: "#",
    id: 1,
  },
  {
    title: "Adhesives & Sealants",
    icon: "fa6-solid:tape",
    key: "adhesives-sealants",
    url: "#",
    id: 2,
  },
  {
    title: "Electrical & Electronics",
    icon: "fa6-solid:plug-circle-bolt",
    key: "electrical-electronics",
    url: "#",
    id: 3,
  },
  {
    title: "Home & Personal Care",
    icon: "fa6-solid:utensils",
    key: "home-personal-care",
    url: "#",
  },
  {
    title: "Paints & Coating",
    icon: "fa6-solid:paint-roller",
    key: "paints-coating",
    url: "#",
    id: 4,
  },
  {
    title: "Agriculture & Animal Feed",
    icon: "fa6-solid:tractor",
    key: "agriculture-animal-feed",
    url: "#",
  },
  {
    title: "Pharmaceutical & Nutraceutical",
    icon: "fa6-solid:syringe",
    key: "pharmaceutical-nutraceutical",
    url: "#",
  },
  {
    title: "Research & Development",
    icon: "fa6-solid:flask",
    key: "research-development",
    url: "#",
  },
  {
    title: "Food & Nutrition",
    icon: "fa6-solid:plate-wheat",
    key: "food-nutrition",
    url: "#",
  },
  {
    title: "Industrial",
    icon: "fa6-solid:industry",
    key: "industrial",
    url: "#",
  },
  {
    title: "Oil & Gas",
    icon: "fa6-solid:oil-well",
    key: "oil-gas",
    url: "#",
  },
  {
    title: "Building & Construction",
    icon: "fa6-solid:person-digging",
    key: "building-construction",
    url: "#",
  },
  {
    title: "Printing & Packaging",
    icon: "fa6-solid:box",
    key: "printing-packaging",
    url: "#",
  },
  {
    title: "Mining",
    icon: "fa6-solid:gem",
    key: "mining",
    url: "#",
  },
  {
    title: "Water Treatment",
    icon: "fa6-solid:glass-water-droplet",
    key: "water-treatment",
    url: "#",
  },

  {
    title: "Automotive & Transportation",
    icon: "fa6-solid:car",
    key: "automotive-transportation",
    url: "#",
  },
];

//   navs
export const navigations = [
  {
    name: "Markets",
    key: "markets",
    url: null,
  },
  {
    name: "Applications",
    key: "applications",
    url: null,
  },
  {
    name: "Finance",
    key: "finance",
    url: "/finance",
  },
];
export const mobileNavigation = [
  {
    name: "All categories",
    key: "categories",
  },
];

export const mobileMenu = [
  {
    name: "Dashboard",
    url: "/overview",
    icon: "mingcute:layout-3-line",
    key: "overview",
  },

  {
    name: "My orders",
    key: "my-orders",
    icon: "solar:box-bold",
    url: "/procurement/my-orders",
  },
  {
    name: "My requests",
    key: "my-requests",
    icon: "gridicons:cart",
    url: "/procurement/my-requests",
  },
  {
    name: "Shipping address",
    key: "shipping",
    icon: "fa6-solid:address-book",
    url: "/procurement/shipping-addresses",
  },
  {
    name: "Wallet",
    key: "wallet",
    icon: "ion:wallet",
    url: "/wallet/home",
  },
  {
    name: "Saved items",
    key: "saved",
    icon: "ri:heart-fill",
    url: "/account/saved-searches",
  },
  {
    name: "Storefront",
    key: "storefront",
    icon: "fa6-solid:store",
    url: "/storefront/customization",
  },
  {
    name: "Company settings",
    key: "company",
    icon: "clarity:building-solid",
    url: "/company/settings",
  },
  {
    name: "User Management",
    url: "/users",
    icon: "lucide:users",
    key: "user",
  },
  {
    name: "Products",
    url: "/storefront/products",
    icon: "fluent-mdl2:product-variant",
    key: "products",
  },
  {
    name: "Account settings",
    url: "/settings",
    icon: "lucide:user",
    key: "settings",
  },
  {
    name: "Sign out",
    key: "sign-out",
    icon: "fa-solid:sign-out-alt",
    url: "#",
  },
];

export const financeMenu = [
  {
    title: "Trade Finance",
    key: "trade-finance",
    url: "#",
  },
  {
    title: "Supply Finance",
    key: "supply-finance",
    url: "#",
  },
  {
    title: "Import Finance",
    key: "import-finance",
    url: "#",
  },
  {
    title: "Export Finance",
    key: "export-finance",
    url: "#",
  },
  {
    title: "Cross-Border Payments",
    key: "cross-border-payments",
    url: "#",
  },
];

export const hotDeals = [
  {
    title: "Ammonia Liquor",
    company: "A Huber Company",
    img: "/images/1.png",
    oldprice: "3300",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Hydrogenated Castor Oil",
    company: "Bisley International LLC",
    img: "/images/2.png",
    oldprice: "3300",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Hydrotint Black Paste",
    company: "GCP Applied Technologies Inc",
    img: "/images/3.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "IPEA (N,N-Diisopropylethylamine)",
    company: "SASOL Chemicals",
    img: "/images/4.png",
    oldprice: "",
    newprice: "",
    type: "request",
  },
];

export const bestSellers = [
  {
    title: "Kronos 2190 (Titanium Dioxide)",
    company: "A Huber Company",
    img: "/images/5.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/7.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/6.png",
    oldprice: "3300",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "IPEA (N,N-Diisopropylethylamine)",
    company: "SASOL Chemicals",
    img: "/images/8.png",
    oldprice: "",
    newprice: "",
    type: "request",
  },
];
export const reccomended = [
  {
    title: "Kronos 2190 (Titanium Dioxide)",
    company: "A Huber Company",
    img: "/images/9.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "3300",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "IPEA (N,N-Diisopropylethylamine)",
    company: "SASOL Chemicals",
    img: "/images/4.png",
    oldprice: "",
    newprice: "",
    type: "request",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "3300",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "3300",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
];
export const market = [
  {
    title: "Kronos 2190 (Titanium Dioxide)",
    company: "A Huber Company",
    img: "/images/9.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "IPEA (N,N-Diisopropylethylamine)",
    company: "SASOL Chemicals",
    img: "/images/4.png",
    oldprice: "",
    newprice: "",
    type: "request",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "",
    newprice: "",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Kronos 2190 (Titanium Dioxide)",
    company: "A Huber Company",
    img: "/images/9.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "IPEA (N,N-Diisopropylethylamine)",
    company: "SASOL Chemicals",
    img: "/images/4.png",
    oldprice: "",
    newprice: "",
    type: "request",
  },
  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "",
    newprice: "",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },

  {
    title: "Linear Low Density Polyethylene (LLDPE)",
    company: "GCP Applied Technologies Inc",
    img: "/images/10.png",
    oldprice: "",
    newprice: "3800",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
  {
    title: "Industrial Salt",
    company: "Bisley International LLC",
    img: "/images/11.png",
    oldprice: "",
    newprice: "2500",
    type: "sale",
    id: 1,
    category: "Adhesive",
  },
];
