export const timezoneCountryMapping = {
  // Africa
  'Africa/Abidjan': 'Ivory Coast',
  'Africa/Accra': 'Ghana',
  'Africa/Addis_Ababa': 'Ethiopia',
  'Africa/Algiers': 'Algeria',
  'Africa/Asmara': 'Eritrea',
  'Africa/Bamako': 'Mali',
  'Africa/Bangui': 'Central African Republic',
  'Africa/Banjul': 'Gambia',
  'Africa/Blantyre': 'Malawi',
  'Africa/Bujumbura': 'Burundi',
  'Africa/Cairo': 'Egypt',
  'Africa/Casablanca': 'Morocco',
  'Africa/Conakry': 'Guinea',
  'Africa/Dakar': 'Senegal',
  'Africa/Dar_es_Salaam': 'Tanzania',
  'Africa/Djibouti': 'Djibouti',
  'Africa/El_Aaiun': 'Western Sahara',
  'Africa/Freetown': 'Sierra Leone',
  'Africa/Gaborone': 'Botswana',
  'Africa/Harare': 'Zimbabwe',
  'Africa/Johannesburg': 'South Africa',
  'Africa/Juba': 'South Sudan',
  'Africa/Kampala': 'Uganda',
  'Africa/Khartoum': 'Sudan',
  'Africa/Kigali': 'Rwanda',
  'Africa/Kinshasa': 'Democratic Republic of the Congo',
  'Africa/Lagos': 'Nigeria',
  'Africa/Libreville': 'Gabon',
  'Africa/Luanda': 'Angola',
  'Africa/Lubumbashi': 'Democratic Republic of the Congo',
  'Africa/Lusaka': 'Zambia',
  'Africa/Malabo': 'Equatorial Guinea',
  'Africa/Maputo': 'Mozambique',
  'Africa/Maseru': 'Lesotho',
  'Africa/Mbabane': 'Eswatini',
  'Africa/Mogadishu': 'Somalia',
  'Africa/Monrovia': 'Liberia',
  'Africa/Nairobi': 'Kenya',
  'Africa/Ndjamena': 'Chad',
  'Africa/Niamey': 'Niger',
  'Africa/Nouakchott': 'Mauritania',
  'Africa/Ouagadougou': 'Burkina Faso',
  'Africa/Porto-Novo': 'Benin',
  'Africa/Sao_Tome': 'São Tomé and Príncipe',
  'Africa/Tripoli': 'Libya',
  'Africa/Tunis': 'Tunisia',
  'Africa/Windhoek': 'Namibia',

  // Americas
  'America/Adak': 'United States',
  'America/Anchorage': 'United States',
  'America/Anguilla': 'Anguilla',
  'America/Antigua': 'Antigua and Barbuda',
  'America/Araguaina': 'Brazil',
  'America/Argentina/Buenos_Aires': 'Argentina',
  'America/Argentina/Catamarca': 'Argentina',
  'America/Argentina/ComodRivadavia': 'Argentina',
  'America/Argentina/Cordoba': 'Argentina',
  'America/Argentina/Jujuy': 'Argentina',
  'America/Argentina/La_Rioja': 'Argentina',
  'America/Argentina/Mendoza': 'Argentina',
  'America/Argentina/Rosario': 'Argentina',
  'America/Argentina/Salta': 'Argentina',
  'America/Argentina/San_Juan': 'Argentina',
  'America/Argentina/San_Luis': 'Argentina',
  'America/Argentina/Tucuman': 'Argentina',
  'America/Argentina/Ushuaia': 'Argentina',
  'America/Asuncion': 'Paraguay',
  'America/Atikokan': 'Canada',
  'America/Bahia': 'Brazil',
  'America/Bahia_Banderas': 'Mexico',
  'America/Barbados': 'Barbados',
  'America/Belem': 'Brazil',
  'America/Belize': 'Belize',
  'America/Blanc-Sablon': 'Canada',
  'America/Boa_Vista': 'Brazil',
  'America/Bogota': 'Colombia',
  'America/Boise': 'United States',
  'America/Cambridge_Bay': 'Canada',
  'America/Campo_Grande': 'Brazil',
  'America/Cancun': 'Mexico',
  'America/Caracas': 'Venezuela',
  'America/Cayenne': 'French Guiana',
  'America/Cayman': 'Cayman Islands',
  'America/Chicago': 'United States',
  'America/Chihuahua': 'Mexico',
  'America/Costa_Rica': 'Costa Rica',
  'America/Cuiaba': 'Brazil',
  'America/Curacao': 'Curacao',
  'America/Danmarkshavn': 'Greenland',
  'America/Dawson': 'Canada',
  'America/Dawson_Creek': 'Canada',
  'America/Denver': 'United States',
  'America/Detroit': 'United States',
  'America/Dominica': 'Dominica',
  'America/Edmonton': 'Canada',
  'America/Eirunepe': 'Brazil',
  'America/El_Salvador': 'El Salvador',
  'America/Fortaleza': 'Brazil',
  'America/Glace_Bay': 'Canada',
  'America/Godthab': 'Greenland',
  'America/Goose_Bay': 'Canada',
  'America/Grand_Turk': 'Turks and Caicos Islands',
  'America/Grenada': 'Grenada',
  'America/Guadeloupe': 'Guadeloupe',
  'America/Guatemala': 'Guatemala',
  'America/Guayaquil': 'Ecuador',
  'America/Guyana': 'Guyana',
  'America/Houston': 'United States',
  'America/Huancayo': 'Peru',
  'America/Iqaluit': 'Canada',
  'America/Jamaica': 'Jamaica',
  'America/Juneau': 'United States',
  'America/Kentucky/Louisville': 'United States',
  'America/Kentucky/Monticello': 'United States',
  'America/Kralendijk': 'Bonaire, Sint Eustatius, and Saba',
  'America/La_Paz': 'Bolivia',
  'America/Lima': 'Peru',
  'America/Los_Angeles': 'United States',
  'America/Louisville': 'United States',
  'America/Maceio': 'Brazil',
  'America/Managua': 'Nicaragua',
  'America/Manaus': 'Brazil',
  'America/Marigot': 'Saint Martin',
  'America/Martinique': 'Martinique',
  'America/Matamoros': 'Mexico',
  'America/Mexico_City': 'Mexico',
  'America/Miquelon': 'Saint Pierre and Miquelon',
  'America/Moncton': 'Canada',
  'America/Monterrey': 'Mexico',
  'America/Montreal': 'Canada',
  'America/Nassau': 'Bahamas',
  'America/New_York': 'United States',
  'America/Nipigon': 'Canada',
  'America/Nome': 'United States',
  'America/Noronha': 'Brazil',
  'America/North_Dakota/Beulah': 'United States',
  'America/North_Dakota/Center': 'United States',
  'America/North_Dakota/New_Salem': 'United States',
  'America/Olinda': 'Brazil',
  'America/Panama': 'Panama',
  'America/Paramaribo': 'Suriname',
  'America/Phoenix': 'United States',
  'America/Port_of_Spain': 'Trinidad and Tobago',
  'America/Porto_Velho': 'Brazil',
  'America/Puerto_Rico': 'Puerto Rico',
  'America/Punta_Arenas': 'Chile',
  'America/Rainy_River': 'Canada',
  'America/Rankin_Inlet': 'Canada',
  'America/Recife': 'Brazil',
  'America/Regina': 'Canada',
  'America/Resolute': 'Canada',
  'America/Rio_Branco': 'Brazil',
  'America/Santa_Isabel': 'Brazil',
  'America/Santarem': 'Brazil',
  'America/Sao_Paulo': 'Brazil',
  'America/Scoresbysund': 'Greenland',
  'America/Sitka': 'United States',
  'America/St_Barthelemy': 'Saint Barthélemy',
  'America/St_Johns': 'Canada',
  'America/St_Kitts': 'Saint Kitts and Nevis',
  'America/St_Lucia': 'Saint Lucia',
  'America/St_Thomas': 'United States',
  'America/Tegucigalpa': 'Honduras',
  'America/Thule': 'Greenland',
  'America/Thunder_Bay': 'Canada',
  'America/Toronto': 'Canada',
  'America/Tortola': 'British Virgin Islands',
  'America/Vancouver': 'Canada',
  'America/Whitehorse': 'Canada',
  'America/Winnipeg': 'Canada',
  'America/Yakutat': 'United States',
  'America/Yellowknife': 'Canada',

  // Asia
  'Asia/Aden': 'Yemen',
  'Asia/Almaty': 'Kazakhstan',
  'Asia/Amman': 'Jordan',
  'Asia/Anadyr': 'Russia',
  'Asia/Aqtau': 'Kazakhstan',
  'Asia/Aqtobe': 'Kazakhstan',
  'Asia/Baghdad': 'Iraq',
  'Asia/Bahrain': 'Bahrain',
  'Asia/Baku': 'Azerbaijan',
  'Asia/Bangkok': 'Thailand',
  'Asia/Barnaul': 'Russia',
  'Asia/Beirut': 'Lebanon',
  'Asia/Bishkek': 'Kyrgyzstan',
  'Asia/Brunei': 'Brunei',
  'Asia/Chita': 'Russia',
  'Asia/Choibalsan': 'Mongolia',
  'Asia/Colombo': 'Sri Lanka',
  'Asia/Damascus': 'Syria',
  'Asia/Dhaka': 'Bangladesh',
  'Asia/Dili': 'East Timor',
  'Asia/Dubai': 'United Arab Emirates',
  'Asia/Dushanbe': 'Tajikistan',
  'Asia/Gaza': 'Palestinian Territories',
  'Asia/Hong_Kong': 'Hong Kong',
  'Asia/Hovd': 'Mongolia',
  'Asia/Irkutsk': 'Russia',
  'Asia/Jakarta': 'Indonesia',
  'Asia/Jayapura': 'Indonesia',
  'Asia/Jerusalem': 'Israel',
  'Asia/Kabul': 'Afghanistan',
  'Asia/Karachi': 'Pakistan',
  'Asia/Kathmandu': 'Nepal',
  'Asia/Kolkata': 'India',
  'Asia/Krasnoyarsk': 'Russia',
  'Asia/Kuala_Lumpur': 'Malaysia',
  'Asia/Kuching': 'Malaysia',
  'Asia/Macau': 'Macau',
  'Asia/Magadan': 'Russia',
  'Asia/Makassar': 'Indonesia',
  'Asia/Manila': 'Philippines',
  'Asia/Muscat': 'Oman',
  'Asia/Nicosia': 'Cyprus',
  'Asia/Novokuznetsk': 'Russia',
  'Asia/Novosibirsk': 'Russia',
  'Asia/Omsk': 'Russia',
  'Asia/Oral': 'Kazakhstan',
  'Asia/Phnom_Penh': 'Cambodia',
  'Asia/Pontianak': 'Indonesia',
  'Asia/Pyongyang': 'North Korea',
  'Asia/Qatar': 'Qatar',
  'Asia/Qyzylorda': 'Kazakhstan',
  'Asia/Riyadh': 'Saudi Arabia',
  'Asia/Sakhalin': 'Russia',
  'Asia/Samarkand': 'Uzbekistan',
  'Asia/Seoul': 'South Korea',
  'Asia/Shanghai': 'China',
  'Asia/Singapore': 'Singapore',
  'Asia/Taipei': 'Taiwan',
  'Asia/Tashkent': 'Uzbekistan',
  'Asia/Tbilisi': 'Georgia',
  'Asia/Tehran': 'Iran',
  'Asia/Tokyo': 'Japan',
  'Asia/Ulaanbaatar': 'Mongolia',
  'Asia/Urumqi': 'China',
  'Asia/Vientiane': 'Laos',
  'Asia/Vladivostok': 'Russia',
  'Asia/Yakutsk': 'Russia',
  'Asia/Yangon': 'Myanmar',
  'Asia/Yekaterinburg': 'Russia',
  'Asia/Yerevan': 'Armenia',

  // Europe
  'Europe/Amsterdam': 'Netherlands',
  'Europe/Andorra': 'Andorra',
  'Europe/Athens': 'Greece',
  'Europe/Belgrade': 'Serbia',
  'Europe/Berlin': 'Germany',
  'Europe/Bratislava': 'Slovakia',
  'Europe/Brussels': 'Belgium',
  'Europe/Bucharest': 'Romania',
  'Europe/Budapest': 'Hungary',
  'Europe/Chisinau': 'Moldova',
  'Europe/Copenhagen': 'Denmark',
  'Europe/Dublin': 'Ireland',
  'Europe/Helsinki': 'Finland',
  'Europe/Lisbon': 'Portugal',
  'Europe/Ljubljana': 'Slovenia',
  'Europe/London': 'United Kingdom',
  'Europe/Luxembourg': 'Luxembourg',
  'Europe/Madrid': 'Spain',
  'Europe/Malta': 'Malta',
  'Europe/Mariehamn': 'Åland Islands',
  'Europe/Minsk': 'Belarus',
  'Europe/Monaco': 'Monaco',
  'Europe/Moscow': 'Russia',
  'Europe/Oslo': 'Norway',
  'Europe/Paris': 'France',
  'Europe/Prague': 'Czech Republic',
  'Europe/Riga': 'Latvia',
  'Europe/Rome': 'Italy',
  'Europe/Samara': 'Russia',
  'Europe/San_Marino': 'San Marino',
  'Europe/Saratov': 'Russia',
  'Europe/Simferopol': 'Crimea',
  'Europe/Sofia': 'Bulgaria',
  'Europe/Stockholm': 'Sweden',
  'Europe/Tallinn': 'Estonia',
  'Europe/Tirane': 'Albania',
  'Europe/Uzhgorod': 'Ukraine',
  'Europe/Vaduz': 'Liechtenstein',
  'Europe/Vatican': 'Vatican City',
  'Europe/Vienna': 'Austria',
  'Europe/Vilnius': 'Lithuania',
  'Europe/Volgograd': 'Russia',
  'Europe/Warsaw': 'Poland',
  'Europe/Zagreb': 'Croatia',
  'Europe/Zaporozhye': 'Ukraine',
};
