name: Build
on:
  push:
    branches:
      - development
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: "d52d0916bb23ea78bb81b78bf42408f845ac7823"
          with:
             args:>
             -Dsonar.organization=matta-trade
